MAX_EPOCHS: 3
batch_size: 1024
do_under_sampling: true
i_global: 2115
lower_SD_thres_for_reasonable_ripple: 1
num_workers: 10
samp_rate: 1000
use_classes_str:
- n
- r
use_random_start: true
window_size_pts: 400
